package logic.pages.reports;

public enum ReportsName {
    IFTA_REPORT("IFTA REPORT"),
    DRIVER_PAYMENT_REPORT("DRIVER PAYMENT REPORT"),
    VIOLATION_REPORT("VIOLATION REPORT"),
    OVERSPEED_REPORT("OVERSPEED REPORT"),
    LOG_AUDITING_REPORT("LOG AUDITING REPORT"),
    ZONE_TRIGGER_REPORT("ZONE TRIGGER REPORT"),
    TRUCK_POSITION_REPORT("TRUCK POSITION REPORT"),
    TRUCK_MOVEMENT_REPORT("TRUCK MOVEMENT REPORT"),
    ELOG_ACTIVITY_REPORT("ELOG ACTIVITY REPORT"),
    ELD_PLATFORMS_AND_VERSIONS_REPORT("ELD PLATFORMS AND VERSIONS"),
    DRIVER_ASSIGNMENT_REPORT("DRIVER ASSIGNMENT REPORT"),
    PROBILL_REPORTS("PROBILL REPORTS"),
    EFS_TRANSACTION_REPORT ("EFS TRANSACTION REPORT"),
    FUEL_CONSUMPTION_AND_PURCHASE_REPORT("FUEL CONSUMPTION AND PURCHASE REPORT"),
    AUDIT_REPORTS("AUDIT REPORTS"),
    AUDIT_REPORTS_ON_THE_ROAD_TRIPS("AUDIT REPORTS ON THE ROAD TRIPS"),
    TRIP_REVENUE_REPORTS ("TRIP REVENUE REPORTS"),
    LENA_REPORT ("LENA REPORT"),
    CITY_DRIVERS_REPORT ("CITY DRIVERS REPORT"),
    KIRK_FUEL_CARDS_REPORT ("KIRK FUEL CARDS REPORT"),
    POD_REPORT ("POD REPORT"),
    DATA_ENTRY_REPORT ("DATA ENTRY REPORT"),
    DRIVERS_HIRED_LEFT_REPORT ("DRIVERS HIRED/LEFT REPORT"),
    NJ_CITY_LIST_DAILY_REPORT ("NJ CITY LIST (DAILY) REPORT"),
    LAYOVER_WAITING_TIME_REPORT ("LAYOVER/WAITING TIME REPORT"),
    EQUIPMENT_MILEAGE_REPORT ("EQUIPMENT MILEAGE REPORT"),
    LA_REPORTS ("LA REPORTS"),
    PIN_REQUEST_REPORT ("PIN REQUEST REPORT"),
    DRIVER_FUEL_PURCHASING_REPORT ("DRIVER FUEL PURCHASING REPORT"),
    DRIVERS_REPORT ("DRIVERS REPORT"),
    TRAILERS_REPORT_REPORT ("TRAILERS REPORT"),
    DRIVER_CASH_FLOW_HISTORY_REPORT ("DRIVER CASH FLOW HISTORY REPORT"),
    EXPENSE_ACCT_HISTORY_REPORT ("EXPENSE ACCT HISTORY REPORT"),
    DRIVERS_BALANCES_REPORT ("DRIVERS BALANCES REPORT"),
    TRAILERS_GPS_DIFFERENCE_REPORT ("TRAILERS GPS DIFFERENCE REPORT"),
    EQUIPMENT_LAST_SCHEDULED_STOP_REPORT ("EQUIPMENT LAST SCHEDULED STOP REPORT"),
    TRUCK_INACTIVITY_REPORT ("TRUCK INACTIVITY REPORT"),
    LA_ACCOUNTING_REPORTS ("LA ACCOUNTING REPORTS"),
    HL_ACCOUNTING_REPORTS ("HL ACCOUNTING REPORTS"),
    EQUIPMENT_WITH_TAGS_REPORT ("EQUIPMENT WITH TAGS REPORT"),
    MISSING_CUSTOMS_DATA_REPORT ("MISSING CUSTOMS DATA REPORT"),
    MISSING_PROOF_OF_DELIVERY_REPORT ("MISSING PROOF OF DELIVERY REPORT"),
    ISSUED_MONEY_CODES_REPORT ("ISSUED MONEY CODES REPORT"),
    LIST_OF_DEDUCTIONS_FROM_SALARY ("LIST OF DEDUCTIONS (REFUNDS) FROM (TO) SALARY"),
    DRIVER_INSURANCE_AND_SAFETY_BONUS_REPORT ("DRIVER'S INSURANCE AND SAFETY BONUS REPORT"),
    FINAL_ACCOUNTING_REPORT ("FINAL ACCOUNTING REPORT"),
    CURRENCY_EXCHANGE_REPORT ("CURRENCY EXCHANGE REPORT");



    public final String reportName;

    ReportsName(String reportName) {
        this.reportName = reportName;
    }

    public String getReportName() {
        return reportName;
    }
}
